### ISSUE TITLE
design

### ISSUE THREAD

**Issue by MizukiSonoko** [hyperledger/iroha-python#1]
I propose this.

## Archtecture
```
iroha
├── transaction.py
|    ├── Builder
|    └── Validator
├── repository.py
|    ├── AssetRepo
|    └── TransactionRepo
├── crypto.py
|    ├── Hash
|    └── KeyPair
└── connection.py
```

**Comment by Warchant** [comment]
Also, what is the purpose of using `tox` as testing library? Why not [`unittest`](https://docs.python.org/3.5/library/unittest.html)?

**Comment by MizukiSonoko** [comment]
Using wiki is better.
So could you read [wiki](https://github.com/hyperledger/iroha-python/wiki)
