### ISSUE TITLE
Iroha2-python expects the Rust environment, installed by Rustup

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-python#105]
According to @QuentinI, currently this can be fixed by changing the environment variable.

```bash
export RUSTUP_TOOLCHAIN=whatever
```

Version used: [QuentinI/iroha-python/tree/update](https://github.com/QuentinI/iroha-python/tree/update)
Commit used: https://github.com/hyperledger/iroha-python/commit/19bd94f6fc39e059df2264f382fe4765f25e3dfc

**Comment by QuentinI** [comment]
The problem is in iroha2 itself.
