### ISSUE TITLE
Broken imports (iroha2 branch)

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-python#109]
Yesterday, @baziorek found a weird import behavior in `Iroha-python`.

If he runs a command `python3 -c "import iroha2; print(dir(iroha2))"`, this exception appears:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/agh/Pulpit/blockchain/iroha_code/iroha2/iroha-python/iroha2/__init__.py", line 2, in <module>
    from .sys import Client as _Client
  File "/home/agh/Pulpit/blockchain/iroha_code/iroha2/iroha-python/iroha2/sys/__init__.py", line 1, in <module>
    from ..iroha2 import *
ModuleNotFoundError: No module named 'iroha2.iroha2'
```

This repeats on:
* [`git@github.com:hyperledger/iroha-python.git`](https://github.com/hyperledger/iroha-python/tree/iroha2), the `iroha2` branch
* [`git@github.com:QuentinI/iroha-python.git`](https://github.com/QuentinI/iroha-python/tree/update), the `update` branch.

Context:

* pip 22.1.2 from /home/agh/.local/lib/python3.10/site-packages/pip (python 3.10)
* Python 3.10.5
* `~/.local/lib/python3.10/site-packages/` contains `iroha2` and `iroha_python-0.1.0.dist-info`

**Comment by baziorek** [comment]
Interesting thing is that after changing current directory from `iroha-python` it is working:
```
➜ python3 -m venv virtual_environment_name                                                                
➜ source virtual_environment_name/bin/activate
(virtual_environment_name) ➜  iroha2-python_tmp git clone -b iroha2 https://github.com/hyperledger/iroha-python.git  
(virtual_environment_name) ➜ cd iroha-python
(virtual_environment_name) ➜ pip3 install maturin
(virtual_environment_name) ➜ export RUSTUP_TOOLCHAIN=whatever
(virtual_environment_name) ➜ maturin build
(virtual_environment_name) ➜ pip3 install ./target/wheels/iroha_python-*.whl 
(virtual_environment_name) ➜ python3 -c "import iroha2; print(dir(iroha2))"                                                                                                                   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/agh/Pulpit/blockchain/iroha_code/iroha2-python_tmp/iroha-python/iroha2/__init__.py", line 2, in <module>
    from .sys.rust import *
  File "/home/agh/Pulpit/blockchain/iroha_code/iroha2-python_tmp/iroha-python/iroha2/sys/__init__.py", line 1, in <module>
    from ..iroha2 import *
ModuleNotFoundError: No module named 'iroha2.iroha2'
(virtual_environment_name) ➜ cd ~
(virtual_environment_name) ➜  ~ python3 -c "import iroha2; print(dir(iroha2))"
['ClassPath', 'Client', 'Dict', 'Enum', 'KeyPair', 'List', 'Struct', 'Tuple', '_Client', '_Instruction', '_Query', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'data_model', 'get_class', 'import_module', 'iroha2', 'query', 'sys', 'to_rust']
```

**Comment by 6r1d** [comment]
Great, so that was a normal behavior for Python, not exactly a bug. I believe it is made so for developing modules: you open a normal Python REPL and import directories.

**Comment by baziorek** [comment]
> Great, so that was a normal behavior for Python, not exactly a bug. I believe it is made so for developing modules: you open a normal Python REPL and import directories.

I suggest to add information to documentation: https://hyperledger.github.io/iroha-2-docs/guide/python.html#_1-iroha-2-client-setup
probably more people would have the problem. I was going step by step according to the documentation:D.

**Comment by 6r1d** [comment]
> I suggest to add information to documentation: https://hyperledger.github.io/iroha-2-docs/guide/python.html#_1-iroha-2-client-setup
This is certainly a good idea, I'll update those docs as well.
