### ISSUE TITLE
Functions to create genesis block missing

### ISSUE THREAD

**Issue by baziorek** [hyperledger/iroha-python#57]
In official iroha's documentation I see example of directly creating genesis block ([here](https://iroha.readthedocs.io/en/master/develop/api/permissions.html#command-related-permissions)). It is code from [documentation](https://iroha.readthedocs.io/en/master/develop/api/permissions.html#command-related-permissions):

```
admin = commons.new_user('admin@test')
alice = commons.new_user('alice@test')
bob = commons.new_user('bob@test')
iroha = Iroha(admin['id'])

@commons.hex
def genesis_tx():
    test_permissions = [primitive_pb2.can_create_account]
    genesis_commands = commons.genesis_block(admin, alice, test_permissions)
    tx = iroha.transaction(genesis_commands)
    IrohaCrypto.sign_transaction(tx, admin['key'])
    return tx

@commons.hex
def create_account_tx():
    tx = iroha.transaction([
        iroha.command('CreateAccount', account_name='bob', domain_id='test', public_key=bob['key'])
    ], creator_account=alice['id'])
    IrohaCrypto.sign_transaction(tx, alice['key'])
    return tx
```

But in library code I don't see functions: `commons.genesis_block`. On the other hand I see that functionalities in [java's part of documentation](https://iroha.readthedocs.io/en/master/develop/libraries/java.html#example-code):
```
private static BlockOuterClass.Block getGenesisBlock() {
    return new GenesisBlockBuilder()
        // first transaction
        .addTransaction(
            // transactions in genesis block can have no creator
            Transaction.builder(null)
                // by default peer is listening on port 10001
                .addPeer("0.0.0.0:10001", peerKeypair.getPublic())
                // create default "user" role
                .createRole(userRole,
                    Arrays.asList(
                        RolePermission.can_transfer,
                        RolePermission.can_get_my_acc_ast,
                        RolePermission.can_get_my_txs,
                        RolePermission.can_receive
                    )
                )
                .createDomain(bankDomain, userRole)
                // create user A
                .createAccount("user_a", bankDomain, useraKeypair.getPublic())
                // create user B
                .createAccount("user_b", bankDomain, userbKeypair.getPublic())
                // create usd#bank with precision 2
                .createAsset(usdName, bankDomain, 2)
                // transactions in genesis block can be unsigned
                .build() // returns ipj model Transaction
                .build() // returns unsigned protobuf Transaction
        )
        // we want to increase user_a balance by 100 usd
        .addTransaction(
            Transaction.builder(user("user_a"))
                .addAssetQuantity(usd, new BigDecimal("100"))
                .build()
                .build()
        )
        .build();
  }
```

**Comment by v3ss0n** [comment]
Everything is missing , iroha is a beautiful piece of sotware yet  , i don't know where the library are doing 
Incompletion everywhere. I think they move on to 2.0 while 1.x still in very unstable state.
The worst is documentation

**Comment by baziorek** [comment]
About the issue I've found that code, what I was asking about
https://iroha.readthedocs.io/en/master/develop/api/permissions.html#supplementary-sources
About lack of documentation - fortunately on chat they are helping: https://chat.hyperledger.org/channel/iroha with the code:).

**Comment by jpramirez** [comment]
All of these links are defunc. by August 2021 
I will add t the first comment, iroha seems to be an amazing piece of sofware, and an enourmous help for future iplementations of Blockchaing technologies but. the inability to create coherent documentation, and unsupporte packages (c'mon build example is using an ubuntu 16.04..) makes it hard to believe that we can use it for serious implementations, creating an overhead for startups all around that desire to use and even being able to support it (financially also)

**Comment by baziorek** [comment]
> All of these links are defunc. by August 2021
> I will add t the first comment, iroha seems to be an amazing piece of sofware, and an enourmous help for future iplementations of Blockchaing technologies but. the inability to create coherent documentation, and unsupporte packages (c'mon build example is using an ubuntu 16.04..) makes it hard to believe that we can use it for serious implementations, creating an overhead for startups all around that desire to use and even being able to support it (financially also)

They are, because `master` branch has been changed into `main`, here are working links:
https://iroha.readthedocs.io/en/main/develop/api/permissions.html#supplementary-sources

But link to chat is still working, if You have problem with joining You can use telegram, or gitter, [details](https://wiki.hyperledger.org/display/iroha/Hyperledger+Iroha)
