### ISSUE TITLE
[Question] how to list the blocks ?

### ISSUE THREAD

**Issue by shazz** [hyperledger/iroha-python#70]
Hi,

Is it possible thru the python client to list (and maybe filter) the blocks?

Thanks!

**Comment by rietesh** [comment]
from iroha import Iroha, IrohaCrypto


query = iroha.query([        iroha.command('GetBlock',                      height = your_desired_height)    ])
IrohaCrypto.sign_query(query, PRIVATE_KEY)
response = net.send_query(query)
data = response.blockresponse
print(data)

**Comment by shazz** [comment]
Thanks!
