### ISSUE TITLE
TxPaginationMeta not working in GetPendingTransactions

### ISSUE THREAD

**Issue by Pawlak00** [hyperledger/iroha-python#78]
TxPaginationMeta is not working in GetPendingTransactions, When page_size is specified, returned queries are not paged. 
Example : https://gist.github.com/baziorek/64cc66856d9a7ed6833598050ccc610b
Proposal of fix: https://github.com/Pawlak00/iroha-python/commit/b6d7f421fa51200fe5e006585812d77c2f872a6a
cc @baziorek 

Change does not affect other queries using TxPaginationMeta: GetAccountTransactions and GetAccountAssetTransactions

**Comment by baziorek** [comment]
Here is screen of the change (https://github.com/Pawlak00/iroha-python/commit/b6d7f421fa51200fe5e006585812d77c2f872a6a) in case of merging commits:
![image](https://user-images.githubusercontent.com/15332594/128145327-ae5b9f0f-b4cb-46f3-ab4b-77d42ec90355.png)

**Comment by Pawlak00** [comment]
@LiraLemur it was solved in one of my PRs

**Comment by baziorek** [comment]
> @LiraLemur it was solved in one of my PRs

True, it is:
https://github.com/Pawlak00/iroha-python/commit/b6d7f421fa51200fe5e006585812d77c2f872a6a
You can close its:)

**Comment by LiraLemur** [comment]
@Pawlak00 I cannot find the PR here, only the commit. Can you please share the PR number with me?

**Comment by Pawlak00** [comment]
> @Pawlak00 I cannot find the PR here, only the commit. Can you please share the PR number with me?

https://github.com/hyperledger/iroha-python/pull/77
